# ---- dev stage ----
FROM golang:1.23-alpine

# Install required tools
RUN apk add --no-cache \
    git \
    curl \
    bash

WORKDIR /app

# Install AIR for hot reload
RUN go install github.com/air-verse/air@v1.52.3

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Expose app port
EXPOSE 8080

# Default command: hot reload
CMD ["air", "-c", "air.toml"]

